### ISSUE TITLE
Culture in v2.0.0.5 isn't a valid value & causes XRMToolbox to fail to load

### ISSUE THREAD

**Issue by DerekHAu** [AmraouiH/Entity-Field-Analyser#2]
Hi,

In your latest release in EntityieldsAnalyser/Properties/AssemblyInfo.cs on Line 15, the culture identifier isn't a valid value so XRM toolbox won't load with this value/version.

Thanks @abdelkayoumd :)

**Comment by AmraouiH** [comment]
Hello @DerekHAu,

Glad to hear from you, and sorry for the inconvenience.

The fix is published(v2.0.0.6), there's no way to update the tool from Xrmtoolbox because the culture issue can't let Xrmtoolbox app lunch normally.

As a solution, you should navigate to C:\Users\XXX\AppData\Roaming\MscrmTools\XrmToolBox\Plugins, and delete EntityFieldsAnalyser.dll from the plugins list, and relunch the Xrmtoolbox, then reinstall the EntityFieldsAnalyser.

Thank you for your report.
Hamza

**Comment by DerekHAu** [comment]
Hi Hamza,

Thanks. It was reported by a colleague and we had already removed the DLL as he needed to use other XRMToolbox tools. He is downloading the updated version now.

Many thanks for your speedy response & resolution.

Derek
